version: "3.7"
services:
  postgres:
    image: postgres:12.2-alpine
    container_name: postgres
    restart: always
    ports:
      - ${PostgresPort}:${PostgresPort}
    environment:
      POSTGRES_DB: ${PostgresName}
      POSTGRES_USER: ${PostgresUser}
      POSTGRES_PASSWORD: ${PostgresPass}
      PGDATA: /var/lib/postgresql/data/pgdata
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    environment:
      NAME: ${MongoDBName}
      MONGO_INITDB_ROOT_USERNAME: ${MongoDBUser}
      MONGO_INITDB_ROOT_PASSWORD: ${MongoDBPass}
    ports:
      - ${MongoDBPort}:${MongoDBPort}
    volumes:
      - ./mongo_data:/data/db
  postgres_test:
    image: postgres:12.2-alpine
    container_name: postgres_test
    restart: always
    ports:
      - ${PostgresTestPort}:${PostgresPort}
    environment:
      POSTGRES_DB: ${PostgresTestName}
      POSTGRES_USER: ${PostgresUser}
      POSTGRES_PASSWORD: ${PostgresPass}
      PGDATA: /var/lib/postgresql/data/pgdata
  mongo_test:
    image: mongo:latest
    restart: always
    container_name: mongo_test
    environment:
      NAME: ${MongoTestName}
      MONGO_INITDB_ROOT_USERNAME: ${MongoDBUser}
      MONGO_INITDB_ROOT_PASSWORD: ${MongoDBPass}
    ports:
      - ${MongoTestPort}:${MongoDBPort}