version: "3.7"
services:
  postgres:
    image: postgres:12.2-alpine
    container_name: postgres
    restart: always
    ports:
      - ${PostgresPort}:${PostgresPort}
    environment:
      POSTGRES_DB: ${PostgresName}
      POSTGRES_USER: ${PostgresUser}
      POSTGRES_PASSWORD: ${PostgresPass}
      PGDATA: /var/lib/postgresql/data/pgdata
#    volumes:
#      - ./pg_data:/var/lib/postgresql/data/pgdata
  postgres_test:
    image: postgres:12.2-alpine
    container_name: postgres_test
    restart: always
    ports:
      - ${PostgresTestPort}:${PostgresPort}
    environment:
      POSTGRES_DB: ${PostgresTestName}
      POSTGRES_USER: ${PostgresUser}
      POSTGRES_PASSWORD: ${PostgresPass}
      PGDATA: /var/lib/postgresql/data/pgdata